import Link from 'next/link'
import './globals.css'
import './layout.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">          
        <div className="menu_component" >
          <Link href="/">Home</Link>
        </div>
        <div className="menu_component" >
          <Link href="/about_us">About Us</Link>
        </div>
        <div className="menu_component" >
          <Link href="/quiz">Quiz</Link>
        </div>
        <div className="menu_component" >
          <Link href="/contents">Contents</Link>
        </div>          
        </div>{children}</body>
    </html>
  )
}
